org.gradle.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/gradle_gc.log -Xmx5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8  -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xmx5g,Xlog:gc*:file=/home/runner/work/Telltale/Telltale/kotlin_gc.log
kotlin.build.report.output=build_scan
android.useAndroidX=true
org.gradle.cache=true
ksp.useKSP2=true
